/**
 * 에이전트 타입 정의 (42개 에이전트)
 */

export const AGENT_TYPES = {
  // 오케스트레이터
  ORCHESTRATOR: 'orchestrator',
  DATA_COLLECTION_ORCH: 'data_collection_orchestrator',
  DATA_ANALYSIS_ORCH: 'data_analysis_orchestrator',
  LLM_PROCESSING_ORCH: 'llm_processing_orchestrator',
  REPORT_GENERATION_ORCH: 'report_generation_orchestrator',

  // 데이터 수집 (9개)
  MARKET_SCANNER: 'market_scanner',
  COMPANY_INFO_COLLECTOR: 'company_info_collector',
  COMPREHENSIVE_DATA_COLLECTOR: 'comprehensive_data_collector',
  FINANCIAL_DATA_COLLECTOR: 'financial_data_collector',
  NEWS_COLLECTOR: 'news_collector',
  INVESTMENT_INFO_COLLECTOR: 'investment_info_collector',
  ETF_INDEX_COLLECTOR: 'etf_index_collector',
  INCREMENTAL_DATA_COLLECTOR: 'incremental_data_collector',

  // 분석 (5개)
  TECHNICAL_ANALYSIS: 'technical_analysis',
  FUNDAMENTAL_ANALYSIS: 'fundamental_analysis',
  NEWS_ANALYSIS: 'news_analysis',
  FINANCIAL_MARKET_ANALYZER: 'financial_market_analyzer',

  // LLM 처리 (4개)
  COMPREHENSIVE_ANALYSIS: 'comprehensive_analysis',
  INVESTMENT_RECOMMENDATION: 'investment_recommendation',
  FINANCIAL_LLM_ANALYZER: 'financial_llm_analyzer',

  // 보고서 생성 (3개)
  INDIVIDUAL_REPORT_GENERATOR: 'individual_report_generator',
  PORTFOLIO_REPORT_GENERATOR: 'portfolio_report_generator',

  // 검증 및 모니터링
  DATA_FRESHNESS_VALIDATOR: 'data_freshness_validator',
  RESULT_QUALITY_VALIDATOR: 'result_quality_validator',
  REAL_TIME_MONITOR: 'real_time_monitor',
  WORKFLOW_METRICS_COLLECTOR: 'workflow_metrics_collector',

  // 워크플로우 제어
  AGENT_RETRY_HANDLER: 'agent_retry_handler',
  CHECKPOINT_MANAGER: 'checkpoint_manager',
  PARALLEL_EXECUTOR: 'parallel_executor',
  DYNAMIC_AGENT_SELECTOR: 'dynamic_agent_selector',
  MULTI_LLM_HANDLER: 'multi_llm_handler',

  // 지원
  USER_REQUEST_HANDLER: 'user_request_handler',
  INTENT_ANALYZER: 'intent_analyzer'
};

export const AGENT_CATEGORIES = {
  ORCHESTRATOR: 'orchestrator',
  COLLECTOR: 'collector',
  ANALYZER: 'analyzer',
  LLM_PROCESSOR: 'llm_processor',
  REPORTER: 'reporter',
  VALIDATOR: 'validator',
  MONITOR: 'monitor',
  SUPPORT: 'support',
  WORKFLOW_CONTROL: 'workflow_control'
};

// 에이전트 → 카테고리 매핑
export const AGENT_CATEGORY_MAP = {
  [AGENT_TYPES.ORCHESTRATOR]: AGENT_CATEGORIES.ORCHESTRATOR,
  [AGENT_TYPES.DATA_COLLECTION_ORCH]: AGENT_CATEGORIES.ORCHESTRATOR,
  [AGENT_TYPES.DATA_ANALYSIS_ORCH]: AGENT_CATEGORIES.ORCHESTRATOR,
  [AGENT_TYPES.LLM_PROCESSING_ORCH]: AGENT_CATEGORIES.ORCHESTRATOR,
  [AGENT_TYPES.REPORT_GENERATION_ORCH]: AGENT_CATEGORIES.ORCHESTRATOR,

  [AGENT_TYPES.MARKET_SCANNER]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.COMPANY_INFO_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.COMPREHENSIVE_DATA_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.FINANCIAL_DATA_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.NEWS_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.INVESTMENT_INFO_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.ETF_INDEX_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,
  [AGENT_TYPES.INCREMENTAL_DATA_COLLECTOR]: AGENT_CATEGORIES.COLLECTOR,

  [AGENT_TYPES.TECHNICAL_ANALYSIS]: AGENT_CATEGORIES.ANALYZER,
  [AGENT_TYPES.FUNDAMENTAL_ANALYSIS]: AGENT_CATEGORIES.ANALYZER,
  [AGENT_TYPES.NEWS_ANALYSIS]: AGENT_CATEGORIES.ANALYZER,
  [AGENT_TYPES.FINANCIAL_MARKET_ANALYZER]: AGENT_CATEGORIES.ANALYZER,

  [AGENT_TYPES.COMPREHENSIVE_ANALYSIS]: AGENT_CATEGORIES.LLM_PROCESSOR,
  [AGENT_TYPES.INVESTMENT_RECOMMENDATION]: AGENT_CATEGORIES.LLM_PROCESSOR,
  [AGENT_TYPES.FINANCIAL_LLM_ANALYZER]: AGENT_CATEGORIES.LLM_PROCESSOR,

  [AGENT_TYPES.INDIVIDUAL_REPORT_GENERATOR]: AGENT_CATEGORIES.REPORTER,
  [AGENT_TYPES.PORTFOLIO_REPORT_GENERATOR]: AGENT_CATEGORIES.REPORTER,

  [AGENT_TYPES.DATA_FRESHNESS_VALIDATOR]: AGENT_CATEGORIES.VALIDATOR,
  [AGENT_TYPES.RESULT_QUALITY_VALIDATOR]: AGENT_CATEGORIES.VALIDATOR,

  [AGENT_TYPES.REAL_TIME_MONITOR]: AGENT_CATEGORIES.MONITOR,
  [AGENT_TYPES.WORKFLOW_METRICS_COLLECTOR]: AGENT_CATEGORIES.MONITOR,

  [AGENT_TYPES.AGENT_RETRY_HANDLER]: AGENT_CATEGORIES.WORKFLOW_CONTROL,
  [AGENT_TYPES.CHECKPOINT_MANAGER]: AGENT_CATEGORIES.WORKFLOW_CONTROL,
  [AGENT_TYPES.PARALLEL_EXECUTOR]: AGENT_CATEGORIES.WORKFLOW_CONTROL,
  [AGENT_TYPES.DYNAMIC_AGENT_SELECTOR]: AGENT_CATEGORIES.WORKFLOW_CONTROL,
  [AGENT_TYPES.MULTI_LLM_HANDLER]: AGENT_CATEGORIES.WORKFLOW_CONTROL,

  [AGENT_TYPES.USER_REQUEST_HANDLER]: AGENT_CATEGORIES.SUPPORT,
  [AGENT_TYPES.INTENT_ANALYZER]: AGENT_CATEGORIES.SUPPORT
};

// 에이전트 표시 이름
export const AGENT_DISPLAY_NAMES = {
  [AGENT_TYPES.ORCHESTRATOR]: 'Main Orchestrator',
  [AGENT_TYPES.DATA_COLLECTION_ORCH]: 'Data Collection',
  [AGENT_TYPES.DATA_ANALYSIS_ORCH]: 'Data Analysis',
  [AGENT_TYPES.LLM_PROCESSING_ORCH]: 'LLM Processing',
  [AGENT_TYPES.REPORT_GENERATION_ORCH]: 'Report Generation',
  [AGENT_TYPES.MARKET_SCANNER]: 'Market Scanner',
  [AGENT_TYPES.COMPANY_INFO_COLLECTOR]: 'Company Info',
  [AGENT_TYPES.COMPREHENSIVE_DATA_COLLECTOR]: 'Stock Data',
  [AGENT_TYPES.FINANCIAL_DATA_COLLECTOR]: 'Financial Data',
  [AGENT_TYPES.NEWS_COLLECTOR]: 'News',
  [AGENT_TYPES.INVESTMENT_INFO_COLLECTOR]: 'Investment Info',
  [AGENT_TYPES.ETF_INDEX_COLLECTOR]: 'ETF/Index',
  [AGENT_TYPES.INCREMENTAL_DATA_COLLECTOR]: 'Incremental Data',
  [AGENT_TYPES.TECHNICAL_ANALYSIS]: 'Technical',
  [AGENT_TYPES.FUNDAMENTAL_ANALYSIS]: 'Fundamental',
  [AGENT_TYPES.NEWS_ANALYSIS]: 'News Sentiment',
  [AGENT_TYPES.FINANCIAL_MARKET_ANALYZER]: 'Market Analysis',
  [AGENT_TYPES.COMPREHENSIVE_ANALYSIS]: 'AI Analysis',
  [AGENT_TYPES.INVESTMENT_RECOMMENDATION]: 'Recommendation',
  [AGENT_TYPES.FINANCIAL_LLM_ANALYZER]: 'Financial LLM',
  [AGENT_TYPES.INDIVIDUAL_REPORT_GENERATOR]: 'Report Generator',
  [AGENT_TYPES.PORTFOLIO_REPORT_GENERATOR]: 'Portfolio Report',
  [AGENT_TYPES.DATA_FRESHNESS_VALIDATOR]: 'Freshness Check',
  [AGENT_TYPES.RESULT_QUALITY_VALIDATOR]: 'Quality Check',
  [AGENT_TYPES.REAL_TIME_MONITOR]: 'Real-time Monitor',
  [AGENT_TYPES.WORKFLOW_METRICS_COLLECTOR]: 'Metrics Collector',
  [AGENT_TYPES.AGENT_RETRY_HANDLER]: 'Retry Handler',
  [AGENT_TYPES.CHECKPOINT_MANAGER]: 'Checkpoint',
  [AGENT_TYPES.PARALLEL_EXECUTOR]: 'Parallel Executor',
  [AGENT_TYPES.DYNAMIC_AGENT_SELECTOR]: 'Agent Selector',
  [AGENT_TYPES.MULTI_LLM_HANDLER]: 'Multi-LLM',
  [AGENT_TYPES.USER_REQUEST_HANDLER]: 'Request Handler',
  [AGENT_TYPES.INTENT_ANALYZER]: 'Intent Analyzer'
};
